### ISSUE TITLE
Add AWS authentication for downloading data

### ISSUE THREAD

**Issue by aliebrahiiimi** [commoncrawl/cc-index-table#18]
Is it possible to add Amazon Web Services authentication to the download of data?
You described a solution based on Spark that I used. It worked fine, but now it needs authentication.
What are the steps for adding authentication?

**Comment by sebastian-nagel** [comment]
Hi @aliebrahiiimi, could you provide more context what you want to achieve or what code you are running? Is the issue related to the project cc-index-table? For more information about the new scheme to access Common Crawl data, see
- https://commoncrawl.org/2022/03/introducing-cloudfront-access-to-common-crawl-data/
- https://commoncrawl.org/access-the-data/

**Comment by aliebrahiiimi** [comment]
Hi @sebastian-nagel , thanks for your response, yes I want to download cc-index-table.
I have downloaded the index of each file, and now I want to download the folder of each index by using spark-submit, but I can't due to the new rule for amazon authentication.
I have used this tutorial for download: https://github.com/commoncrawl/cc-index-table

**Comment by sebastian-nagel** [comment]
Hi @aliebrahiiimi, thanks - I can reproduce the problem and working on a fix. I'll likely now definitely switch from jets3t to the AWS SDK (see #3) because the latter one supports various authentication methods (EC2 IAM roles, environment variables, credentials file, Java properties - see https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/ec2-iam-roles.html).

**Comment by aliebrahiiimi** [comment]
@sebastian-nagel Thank you very much, yes, it works for me.

**Comment by sebastian-nagel** [comment]
Thanks for the notice, @aliebrahiiimi! Going forward to merge #19.
